package com.smitarani.Week2.entities;

import com.fasterxml.jackson.annotation.JsonProperty;
// Allows us to customize how fields appear in JSON responses.

import jakarta.persistence.*;
// JPA annotations for database mapping (ORM).

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
// Lombok annotations to generate boilerplate code automatically:
// @Getter/@Setter → generates getters and setters
// @AllArgsConstructor → generates constructor with all fields
// @NoArgsConstructor → generates default constructor

import java.time.LocalDate;
// For storing date fields like date of joining.

@Entity
// Marks this class as a JPA entity (table in the database).

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
// Lombok annotations to reduce boilerplate code.

@Table(name = "employees")
// Specifies the table name in the database. If not specified, table name defaults to class name.

public class EmployeeEntity {

    @Id
    // Marks the primary key of the entity.

    @GeneratedValue(strategy = GenerationType.AUTO)
    // Specifies that the primary key is auto-generated by the database.

    private Long id;
    // Unique identifier for each employee.

    private String name;
    // Employee's name.

    private String email;
    // Employee's email.

    private Integer age;
    // Employee's age.

    private LocalDate dateOfJoining;
    // Employee's joining date.

    @JsonProperty("isActive")
    // When converting to JSON, this field will appear as "isActive" instead of "active".

    private Boolean isActive;
    // Indicates if the employee is currently active.

    private String role;
    // Employee role (e.g., ADMIN or USER).

    private Double salary;
    // Employee's salary.
}
